"""Thin adapter over the `gh` CLI.

We shell out rather than using the REST API directly because inside Actions
`gh` is preinstalled and already authenticated via GITHUB_TOKEN -- zero extra
credentials, and the same command works on a laptop.

Every issue we create carries a machine-readable trailer:

    <!-- intuition-id: <16 hex> phi: a,b,c,d -->

That trailer is the join key between an issue and its ledger row, which is how
the feedback pass can label the outcome without any external database.
"""
from __future__ import annotations

import json
import re
import subprocess
from typing import Any

TRAILER = "<!-- intuition-id: {tid} phi: {phi} -->"
TRAILER_RE = re.compile(r"intuition-id:\s*([0-9a-f]{6,})")


def _gh(args: list[str], cwd: str | None = None, timeout: int = 90) -> tuple[int, str, str]:
    try:
        p = subprocess.run(["gh", *args], cwd=cwd, capture_output=True, text=True, timeout=timeout)
        return p.returncode, p.stdout, p.stderr
    except FileNotFoundError:
        return 127, "", "gh CLI not found"
    except subprocess.TimeoutExpired:
        return 124, "", "gh timed out"


def available() -> bool:
    return _gh(["--version"])[0] == 0


def ensure_label(name: str, color: str = "5319e7",
                 desc: str = "Generated by the intuition loop", cwd: str | None = None) -> None:
    _gh(["label", "create", name, "--color", color, "--description", desc, "--force"], cwd)


def list_issues(label: str, state: str = "open", limit: int = 100,
                cwd: str | None = None) -> list[dict[str, Any]]:
    fields = "number,title,body,state,createdAt,closedAt,stateReason,labels,url"
    code, out, _ = _gh(["issue", "list", "--label", label, "--state", state,
                        "--limit", str(limit), "--json", fields], cwd)
    if code != 0 or not out.strip():
        return []
    try:
        return json.loads(out)
    except json.JSONDecodeError:
        return []


def create_issue(title: str, body: str, labels: list[str], tid: str, phi: list[float],
                 dry_run: bool = False, cwd: str | None = None) -> str:
    full = body.rstrip() + "\n\n" + TRAILER.format(
        tid=tid, phi=",".join(f"{x:.4f}" for x in phi)
    )
    if dry_run:
        print(f"[dry-run] issue: {title}\n{full}\n{'-' * 60}")
        return f"dry-run://{tid}"
    args = ["issue", "create", "--title", title, "--body", full]
    for lb in labels:
        args += ["--label", lb]
    code, out, err = _gh(args, cwd)
    if code != 0:
        print(f"[intuition] issue create failed: {err.strip()[:300]}")
        return ""
    return out.strip().splitlines()[-1] if out.strip() else ""


def issue_task_id(issue: dict[str, Any]) -> str | None:
    m = TRAILER_RE.search(issue.get("body") or "")
    return m.group(1) if m else None


def comment(number: int, body: str, dry_run: bool = False, cwd: str | None = None) -> None:
    if dry_run:
        print(f"[dry-run] comment on #{number}: {body[:120]}")
        return
    _gh(["issue", "comment", str(number), "--body", body], cwd)
